title: Stefan Bloemheuvel # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently started my PhD at JADS in the Di-Plast project.
  <br><br>
  My PhD is in the area of industrial machine analysis using data analytics under supervision of Martin Atzmueller.  
  <br><br>
  <b>Contact<b>
  <br><br>
  s.d.bloemheuvel@tue.nl
  
theme: jekyll-theme-minimal

